language: csharp

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty

mono:
  - 4.4.2

dotnet: 2.0.0

script:
  - ./build.sh --verbosity diagnostic --target Deploy

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/GitVersion.CommandLine

deploy:
  on:
    tags: true