language: csharp

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty

mono:
  - 4.4.2

dotnet: 2.0.0

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags

script:
  - ./build.sh --verbosity diagnostic --target Deploy

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/GitVersion.CommandLine

deploy:
  on:
    tags: true