language: csharp

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty

mono: none
dotnet: 2.0.0

script:
  - ./build.sh

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/GitVersion.CommandLine