# common configuration for ALL branches

test: off
cache:
- tools -> build.cake

build_script:
  - ps: .\build.ps1 -Target "Deploy"

artifacts:
  - path: 'artifacts\*.nupkg'

deploy:
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    auth_token:
      secure: irPu6HoTlXrjiN3VU3RKPHeugfWWosgc5BwHTYwlKJuz1uCAm24y3WMmmAjHNdtG
    on:
      appveyor_repo_tag: true       # deploy on tag push only